-- SUPERSEDED — DO NOT RUN
-- This migration added vault_included_until, which was replaced by vault_access_until
-- (see vault_benefit_entitlements.sql). The application reads only vault_access_until.
-- This file is retained for history only.
